# This is a basic workflow to help you get started with Actions

name: Build SD Image
permissions:
  contents: read
  pull-requests: write

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run Build
        run: |
          sudo apt-get install build-essential chrpath cpio debianutils diffstat file gawk gcc git iputils-ping libacl1 liblz4-tool locales python3 python3-git python3-jinja2 python3-pexpect python3-pip python3-subunit socat texinfo unzip wget xz-utils zstd 
          chmod +x kas-yocto-beagleplay-ti-build.sh
          ./kas-yocto-beagleplay-ti-build.sh sd

      # Caches sstate and downloads to speed up subsequent builds        
      - name: Cache sstate + downloads
        uses: actions/cache@v4
        with:
          path: |
            build/sstate-cache
            build/downloads
          key: cache-sstate-downloads
          
      # Uploads the generated SD Image as a build artifact
      - name: Upload SD Image to Github
        uses: actions/upload-artifact@v4
        with:
          name: sd-image
          path: |
            build/deploy-ti/images/beagleplay-ti/*-ti-*.sdimg
